version: "3"
services:
#  docker-mysql:
#    image: mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=0000
#      - MYSQL_DATABASE=forum
#  mysqlclient:
#    depends_on:
#      - docker-mysql
#    image: phpmyadmin
#    restart: on-failure
#    ports:
#      - 8082:80
#    environment:
#      - PMA_ARBITRARY=1
  backend:
#    depends_on:
#      - docker-mysql
    build: ./backend
    ports:
      - "8080:8080"
    restart: on-failure
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "8081:8081"
    restart: on-failure
